before_script:
  - sudo apt-get install pandoc
  # here you can check os environment, it is ubuntu natty  
  - uname -a
  - lsb_release -a

language: python

python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"

env:
  global:
    - MY_SECURE: "CzVJonXL5R68jtbUdkYYLuK9h3q0fWlk1bsh8vBfPJNbm74H0eeqo1Z4vbRl\n2naurz1PBcTqz50APWEfp5cuX1S562ONAONK9SCwb6XvuZSyEUC7TWBUThxI\nTvUfWdZvXg57UZiG2ZOYxwlq8XYe9+5T48TVB7eY+85d8fOROwo="

# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  #- pip install . --use-mirrors

# command to run tests
script: nosetests 
  - echo $MY_SECURE

after_script:
  - env
  - which svn
  - ls -al
